### ISSUE TITLE
Adjust Tagger Taxonomy to auto-populate from query-index

### ISSUE THREAD

**Issue by kunwarsaluja** [hlxsites/channelco-crn-com#114]
Adjust Tagger Taxonomy to auto-populate Author, Keywords, Categories, Templates from the query-index so authors/admins dont have to update it every now and then.

Currently it's manual and being fetched from [here](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/Shared%20Documents/sites/the-channel-company/crn-com/tools/sidekick/[taxonomy.xlsx](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/Shared%20Documents/sites/the-channel-company/crn-com/tools/sidekick/taxonomy.xlsx?d=w10c677b0bd504497a3f237f3e713e59b&csf=1&web=1&e=zKAuOT)?d=w10c677b0bd504497a3f237f3e713e59b&csf=1&web=1&e=zKAuOT) set under[ /scripts/taxonomy.js](https://github.com/hlxsites/channelco-crn-com/blob/main/scripts/taxonomy.js#L7)

See current Tagger page : https://main--channelco-crn-com--hlxsites.hlx.page/tools/sidekick/tagger/tagger.html

**Comment by mfrisbey** [comment]
Reviewing the existing taxonomy document, we have the following lists:

* Template
  * We might be able to use Excel to create a new tab that builds a unique list of all template values in the index.
* Category
  * Propose creating a `helix-categories` tab (similar to existing `helix-authors`) to populate.
* Keywords
  * This one is tricky. The keywords cell contains comma-separated text. I was hoping we could use Excel to split the text, transform the split into cells, transform the cells to rows, then create a unique list of keywords. I haven't been able to figure out how to do that in Excel.
  * As an alternative, we could look into splitting the keyword values when they're coming into the index (i.e. after a publish), then putting the keywords into a separate tab. I don't know how possible that is, plus it would require re-publishing all existing pages.
* Authors
  * Use `helix-authors` tab to populate.

**Comment by kunwarsaluja** [comment]
@mfrisbey let's put a hold on this as the customer dont want this taxonomy to be handled automatically but keep it manual so authors stick to Tagger extension and dont want authors/editors to put any text in the pagemetadata which once published/indexed would show up in the taxonomy sheet if automated.

we can close it for now and reopen incase this comes up again.
