### ISSUE TITLE
Fix the styling for 404 page

### ISSUE THREAD

**Issue by kunwarsaluja** [hlxsites/channelco-crn-com#115]
Fix the styling for 404 page as global fragment styling that includes the trending-stories fragment is rigid

See https://main--channelco-crn-com--hlxsites.hlx.page/404
See https://www.crn.com/404 for reference

![Screenshot 2023-10-11 at 11 30 40 AM](https://github.com/hlxsites/channelco-crn-com/assets/10811320/bef3a662-5a53-4591-a10b-21bd733e2ec6)

Also we'd want to correct the shared.js path so it works on all 404 pages under any directory.

See : https://main--channelco-crn-com--hlxsites.hlx.page/news/internet-of-things/5-industrial-iot-solutions-that-are-solving-big-problems/404

`    import { decorateMain,fetchFragment } from '../../scripts/shared.js';`

**Comment by mfrisbey** [comment]
@kunwarsaluja I had a couple follow up questions:

> global fragment styling that includes the trending-stories fragment is rigid

Are you saying that we shouldn't use a curated trending-stories fragment for this? You're looking for some kind of automatic way of picking the trending stories?

> want to correct the shared.js path so it works on all 404 pages under any directory.

I assume the "bad" behavior we're seeing is that the trending stories content isn't loading on the URL you referenced?

**Comment by kunwarsaluja** [comment]
> Are you saying that we shouldn't use a curated trending-stories fragment for this? You're looking for some kind of automatic way of picking the trending stories?

No i think the fragment way of getting trending stories was fine. I dont see that styling problem anymore as it's now correctly aligned. Might be a recent commit that fixed it

<img width="883" alt="Screen Shot 2023-10-17 at 6 47 07 PM" src="https://github.com/hlxsites/channelco-crn-com/assets/10811320/c5b5d4d1-e291-497a-a1c7-90e95385a4c8">


> I assume the "bad" behavior we're seeing is that the trending stories content isn't loading on the URL you referenced?

I think it's a bad reference in 404 page and might just need an adjustment to the path. Actually it's just quick reference fix that we need to here in 404 page coz in any children pages, it's still trying to find the shared.js.

Let me just fix that reference right now
