### ISSUE TITLE
Need to introduce RSS feed for other global sites

### ISSUE THREAD

**Issue by kunwarsaluja** [hlxsites/channelco-crn-com#130]
Need to introduce RSS feed for other global sites where we can generate RSS feed similar to  https://www.crn.com/rss2.xml

Customer feedback : We have a number of RSS feeds that send out content to various places.  In some cases, we send the full article content in a stream to our publishing partners, like CRN Australia.  How do we do that in Franklin/EDS?
- An rss feed for Australia:  https://www.crn.com/rss2.xml

Customer is still requesting more information around requirements and the needs for it. @mulderjoe would update this ticket once he has more information from global teams.

Feedback from Amol : we have an RSS feed generator script + github workflow in our Block Party submitted by someone in the community that can help you generate and update the RSS feed xml based on when someone publishes an article triggered by Github Events. https://www.hlx.live/developer/block-collection#block-party

**Comment by mulderjoe** [comment]
There are a number of feeds that we display, based on taxonomy. Those are located here:
https://www.crn.com/rss-news-feeds

We also have three other feeds:

- General feed: https://www.crn.com/rss.xml

- Feed that has full content in the feed itself:  https://www.crn.com/rss2.xml  (this feed is specifically for our publishing partners CRN Australia, CRN India and CRN Poland)

- This feed is a news feed for Google:  https://www.crn.com/rss3.xml

**Comment by kunwarsaluja** [comment]
Moved to new github repo : https://github.com/thechannelcompany/crn-com/issues/10
