### ISSUE TITLE
[Issue]Category pages: Include Category value along with Filter 

### ISSUE THREAD

**Issue by varunmitra** [hlxsites/channelco-crn-com#143]
Filtering conditions on category pages, should take category value into account. Right now, filtering on the basis of keywords fetches records from across all categories.
Steps to reproduce:
1. Navigate to a category page like /news/computing
2. Choose a filtering value like Desktop-Clients
3. Notice articles belonging to Channel-News show up

Error Screenshot: 
![2023-10-26 at 10 47 AM](https://github.com/hlxsites/channelco-crn-com/assets/12259186/61105de3-c119-45a4-9600-e4405261d6dc)
Correct Behaviour:
![2023-10-26 at 10 51 AM](https://github.com/hlxsites/channelco-crn-com/assets/12259186/a772387d-d323-42cc-bce9-563812e68e4b)

How To fix: 
Check out method queryMatchingArticlesByCategory in [shared.js](https://github.com/hlxsites/channelco-crn-com/blob/main/scripts/shared.js#L621)

Additional Functionality:
Implement a JS reload when switching between filtering conditions. Similar to what's been done on crn.com. This will allow the queries to run perfectly and reset page Index for previous next buttons

**Comment by kunwarsaluja** [comment]
Closing here. Now tracked under https://github.com/thechannelcompany/crn-com/issues/18
