### ISSUE TITLE
Implement Martec

### ISSUE THREAD

**Issue by kunwarsaluja** [hlxsites/channelco-crn-com#23]
- Google Analytics
- Adobe Analytics
- Google Adsense
- FunnelFuel
- and many more (need to check with customer if we missed any)

All should be loaded in delayed.js to not affect the LHS score.

<hr>

Note : similar was done with another crn site. We can take inspiration from

- https://www.theiotintegrator.com/
- Source at https://github.com/hlxsites/channelco-iot

**Comment by samuelopra** [comment]
you can assign this to me and close this, since it was done as part of ads

**Comment by kunwarsaluja** [comment]
@samuelopra Can you check with customer that all the martec as listed in ticket is included already or we need to add something else ?
