### ISSUE TITLE
[Block] - Category Tags

### ISSUE THREAD

**Issue by mfrisbey** [hlxsites/channelco-crn-com#82]
- [ ] Mobile version
- [ ] Desktop version
- [ ] Autoblock it (if tags exist in page metadata)

See sample at 
- https://www.crn.com/news/computing/

![Screenshot 2023-09-29 at 10 59 27 AM](https://github.com/hlxsites/channelco-crn-com/assets/5108740/81e9c8c1-05eb-4496-9982-624ee03b8986)

May need to ask customer team, but the assumption is that the list of tags should include keywords from the category's articles. Clicking a tag should filter the articles displayed on the page by keyword.

**Comment by kunwarsaluja** [comment]
@mfrisbey I think @samuelopra is also thinking of implementing this as a variation of the news-slider #79 , can you please touch base with him before we start implementing this to avoid duplicate work
