### ISSUE TITLE
[Block] - Category Navigation

### ISSUE THREAD

**Issue by mfrisbey** [hlxsites/channelco-crn-com#83]
- [ ] Mobile version
- [ ] Desktop version
- [ ] Autoblock it (if tags exist in page metadata)

See sample at 
- https://www.crn.com/news/computing/

![Screenshot 2023-09-29 at 11 00 48 AM](https://github.com/hlxsites/channelco-crn-com/assets/5108740/a0e31c26-3f11-49db-9020-0e2e8e0f7547)

Clicking prev/next should navigate, page-by-page, through the current category's articles.

**Comment by kunwarsaluja** [comment]
same as #16 so closing it in favour
